# Goreleaser configuration: http://goreleaser.com
before:
  hooks:
  - make npm-install
  - make fe
builds:
  -
    env:
    - CGO_ENABLED=0
    - GOPATH=/Users/runner/runners/2.162.0/work/web-embed-lab/web-embed-lab/go
    id: "runner"
    binary: "runner"
    main: ./go/src/wel/commands/runner/main/runner.go
    hooks:
      post: make bintarget=dist/runner_darwin_amd64/runner sign
  -
    env:
    - CGO_ENABLED=0
    - GOPATH=/Users/runner/runners/2.162.0/work/web-embed-lab/web-embed-lab/go
    id: "auto-formulate"
    binary: "auto-formulate"
    main: ./go/src/wel/commands/auto-formulate/main/auto-formulate.go
    hooks:
      post: make bintarget=dist/auto-formulate_darwin_amd64/auto-formulate sign

archives:
  -
    builds:
    - "runner"
    - "auto-formulate" 

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: fullstorydev
    name: web-embed-lab
